---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  CacheRootDirectory: "tmp/rubocop_cache"
  Exclude:
    - "vendor/**/*"
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/NestedGroups:
  Enabled: true
  Max: 5

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
